### ISSUE TITLE
Create Return License action

### ISSUE THREAD

**Issue by webbertakken** [webbertakken/unity-actions#17]
As per https://github.com/webbertakken/unity-activate/issues/4 an additional action for returning the license is needed.

**Comment by webbertakken** [comment]
Created new action. Progress can be followed here: https://github.com/webbertakken/unity-return-license

**Comment by webbertakken** [comment]
This is what happens when you try to return a manually activated license.

```console
LICENSE SYSTEM [2019123 14:15:20] Headers:
    HTTP/1.1 400 Bad Request
    Reason: serial was activated manually for this computer and can't be returned
    Vary: Accept-Encoding
    Content-Encoding: deflate
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    Expires: 0
    sc-request-id: 27ae5726-444c-4941-84ec-08d132b337d4
    Content-Type: text/html
    Content-Length: 67
```

**Comment by webbertakken** [comment]
So it looks like for a pro license we have to actually export whatever output the activation process has as a file.

I would expect the output to also be a license file. 

Unlike with the manually activated file, of which the contents have been copied into the  `UNITY_LICENSE` variable by the user, the pro license actually gets generated in the activate action.

That means we have to provide that generated license as an environment  variable for that job, to be used in subsequent jobs. Fortunately GitHub Actions has support for doing this:

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#env (note the part where it supports both job and step level `.env`

This variable can be set like described here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env

I had some trouble before passing an xml file (multiline and with punctuation) back and forth, but now got the whole flow down (the quotes are important):

```bash
# file to var
VARIABLE="$(<someFile)"

# var to output
echo "$VARIABLE"

# var to file (filter user EOL)
echo "$VARIABLE" | tr -d '\r' > someFile

# var to job env var (to be used in subsequent steps)
echo "::set-env name=JOB_VAR::$VARIABLE"
```

The next step would be to get to know the filename.

**Comment by webbertakken** [comment]
@Dyhr since it's unclear to me whether returning a license is based on a license file that is  generated when activating or based on the hardware signature of the editor itself instead.

To find out, i have prepared a specific branch in the `unity-activate` action that you tried, as well as a new action `unity-return-license` with an initial release.

Would you be so kind to test below configuration with your pro license the following?

just put it in a file called `.github/workflows/<your_filename>.yml` in a repository where you have the secrets set to your pro credentials?

```yaml
name: Actions 😎
on: [push]

jobs:
  activateAndThenReturnLicense:
    name: returnLicense 🎈
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL:   ${{ secrets.UNITY_SERIAL }}

    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate Unity
      - name: Activate Unity
        uses: webbertakken/unity-activate@testpro

      # Return License
      - name: Return license
        uses: webbertakken/unity-return-license@v0.1
```
With this we can check 2 things:

1. which files are output by `testpro` branch of `unity-activate`. before and after activating.
2. whether returning a license is based on the editor ID or that we need the output from the job before instead.

Your help would be greatly appreciated, as I can't test it myself without a license.

**Comment by Dyhr** [comment]
Thank you for adding this so quickly.
I tested your current release before I read your response, and it was working fine with v1 of unity-activate.
It's able to active and return the license successfully, but I don't know if you're suppressing any errors as I am just ignoring your UNITY_LICENSE variable entirely.

Here's my config file that works for me:
```
name: Run Tests
on: [push]
jobs:
  requestActivation:
    name: Request activation ✔
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Activate Unity
      uses: webbertakken/unity-activate@v1
      env:
        UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL:   ${{ secrets.UNITY_SERIAL }}
    - name: Run tests
      id: unityTest
      uses: webbertakken/unity-test-runner@v1
      env:
        TEST_MODE: all
    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: Test Results
        path: ${{ steps.unityTest.outputs.artifactsPath }}
    - name: Return license
      uses: webbertakken/unity-return-license@v0.1
      if: always()
```

Let me know if I should still run your branch, or if you need any logs to continue.
