### ISSUE TITLE
Add a 'unityVersion' parameter to the Request Activation File action

### ISSUE THREAD

**Issue by Jibbajabbafic** [webbertakken/unity-actions#30]
This would allow you to easily generate licenses for different versions.

It could be setup similar to the Build action like this:
```
      # Request manual activation file
      - name: Request manual activation file
        uses: webbertakken/unity-request-manual-activation-file@vX
        id: getManualLicenseFile
        with:
         unityVersion: 2019.X.XXXX
```
