### ISSUE TITLE
Use caching to speed up build times

### ISSUE THREAD

**Issue by thorgeirk11** [webbertakken/unity-actions#34]
My unity builds are taking >40 min to build. I am farly new to github actions but I assume the very slow build times is due rebuilding the library folder every time?

![image](https://user-images.githubusercontent.com/2693474/72730443-4e64ab00-3b89-11ea-9b6e-d3c78b56d580.png)

Is there some way I can speed up my build times, e.g. use some kind of caching?

**Comment by thorgeirk11** [comment]
A side note here:
![image](https://user-images.githubusercontent.com/2693474/72730631-a00d3580-3b89-11ea-90aa-e5e07b3d84d6.png)
Why dose it take >2min to setup the webbertakken/unity-return-license@v1 ?

**Comment by webbertakken** [comment]
#### Build times

> My unity builds are taking >40 min to build. I am farly new to github actions but I assume the very slow build times is due rebuilding the library folder every time?
> 
> ![image](https://user-images.githubusercontent.com/2693474/72730443-4e64ab00-3b89-11ea-9b6e-d3c78b56d580.png)
> 
> Is there some way I can speed up my build times, e.g. use some kind of caching?

Hi @thorgeirk11, and thank you for raising this issue. 

I'm not sure why your builds are so slow. `Unity - Builder` builds a project after every update in it's own workflow. The project that's being built is relatively small, but it still has to install libraries.

As you can see in the [actions log here](https://github.com/webbertakken/unity-builder/actions?query=branch%3Amaster+event%3Apush+workflow%3A%22Actions+%F0%9F%98%8E%22) the slowest build (WebGL) takes ~13 minutes, the fastest builds (i.e. StandaloneWindows) take a mere ~4 minutes.

Could you explain the differences between given example and your project? That way we can have an objective look at what can be improved. 

As for caching; this may be possible, but I only want to create an issue for that if we have realistic, actionable steps.

#### Activation process times

> A side note here:
> ![image](https://user-images.githubusercontent.com/2693474/72730631-a00d3580-3b89-11ea-90aa-e5e07b3d84d6.png)
> Why dose it take >2min to setup the webbertakken/unity-return-license@v1 ?

This is because the activation process always exits with the same code. In order to check whether it actually worked, there are two ways to verify this.

- Running any arbitrary command after that requires unity to be activated (current, stable but slow)
- Finding a reliable way to match the output from the activation process and decide whether activation was successful or not (this may differ per unity version, will be a lot faster, maybe desired)

**Comment by webbertakken** [comment]
> This is because the activation process always exits with the same code. In order to check whether it actually worked, there are two ways to verify this.
> 
> Running any arbitrary command after that requires unity to be activated (current, stable but slow)
> Finding a reliable way to match the output from the activation process and decide whether activation was successful or not (this may differ per unity version, will be a lot faster, maybe desired)

This part has been addressed in above MR

**Comment by webbertakken** [comment]
Closing this issue for insufficient further steps to move forward on.

Please create a detailed issue with a description of how you think we can tackle caching or an analysis of how your build is significantly slower on github actions than elsewhere.

This should at least either have some more actionable info or proper steps to reproduce.

**Comment by thorgeirk11** [comment]
I managed to reduce the build time to ~10 min just by caching the library folder!
![image](https://user-images.githubusercontent.com/2693474/73093796-2ce02800-3ed7-11ea-994a-feef4bc32685.png)
```
- name: Cache
  uses: actions/cache@v1.1.0
  with:
    path: Client/Library
    key: Client_Library

- name: Make Unity Client
  uses: webbertakken/unity-builder@v0.8
  env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  with:
    unityVersion: 2018.4.10f1
    targetPlatform: StandaloneWindows64
    buildName: Starborne
    projectPath: Client/
```
