### ISSUE TITLE
A Newbie's Jump Into Unity Actions

### ISSUE THREAD

**Issue by josephbmanley** [webbertakken/unity-actions#39]
Hello there, I've been trying to jump into these actions, but have encountered a few issues. I have not yet built something that had any successful run.

So with the knowledge I have, here what I put together for my action was something like this:

```yaml
name: Build Unity

on:
  push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}


  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      - uses: webbertakken/unity-builder@v0.5
        with:
          unityVersion: 2019.2.11f1
          targetPlatform: StandaloneWindows64
```

So `secrets.UNITY_LICENSE` was generated by going to `Preferences` in Unity Hub then `License Management` and followed `Manual Activation` to get a `.x.ulf` file. The contents of that file were loading into the secret `UNITY_LICENSE`.

So I believe my issue is with understanding of how Unity License management works, hence why I thought a full example may be useful. #14 lol

My goal is the eventually have a pipeline that when there is a release, the project will automatically build to be shipped out with other actions. Perhaps some clarification of where my misunderstanding is and a direction to move towards would be exceptionally useful, thank you!

**Comment by josephbmanley** [comment]
Looks like maybe related to issue #37?

**Comment by webbertakken** [comment]
> So secrets.UNITY_LICENSE was generated by going to Preferences in Unity Hub then License Management and followed Manual Activation to get a .x.ulf file. The contents of that file were loading into the secret UNITY_LICENSE.

Did you upload the file originating from [Unity - Request Activation File](https://github.com/webbertakken/unity-request-manual-activation-file) in order to retrieve your Unity License File?

**Comment by josephbmanley** [comment]
@webbertakken I'll go ahead and give that method a try.

Are you not able to use the activation file generated by Unity Hub?
![Screenshot](https://static.cloudsumu.com/github/unitylicense.png)

**Comment by josephbmanley** [comment]
So it looks like the issue was being caused due to UnityHub generating a license request for 2017.x instead of 2019.x

**Comment by gblikas** [comment]
@josephbmanley I am not sure if this is 100% right, but it looks like if you have multiple license installed via UnityHub, it will return you the last registered license? I tried doing this the way you did and I got a `Unity2017x` license, `Unity2019`, back after running it back-to-back.

**Comment by webbertakken** [comment]
> So it looks like the issue was being caused due to UnityHub generating a license request for 2017.x instead of 2019.x

@josephbmanley I'm glad you figured it out! Could you share what you ended up doing to resolve the problem? Posting your steps may be useful for other people that are experiencing the same or similar trouble.

Also note that I just updated the readme of builder to contain more information about licensing among other things.

**Comment by josephbmanley** [comment]
@gblikas It's weird because I never installed Unity2017 on my machine... Maybe it's last manually activated or something?

@webbertakken Yeah, of course. 

So this is the workflow that ran properly:
```yaml
name: Build Unity

on:
  push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  requestManualActivationFile:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Request manual activation file
      - name: Request manual activation file
        uses: webbertakken/unity-request-manual-activation-file@master
        id: getManualLicenseFile

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Unity - Activate
        uses: webbertakken/unity-activate@master
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      - uses: webbertakken/unity-builder@master
        with:
          unityVersion: 2019.2.11f1
          targetPlatform: StandaloneWindows64
```

The `UNITY_LICENSE` secret was generated by taking the output artifact of the `requestManualActivationFile` job and uploading it to [license.unity3d.com](https://license.unity3d.com). The contents of the output file were placed into the `UNITY_LICENSE` secret. With the secret placed in successfully, the `build` job ran successfully.
