### ISSUE TITLE
Fallback handler could not load library. invalid ELF header.

### ISSUE THREAD

**Issue by gblikas** [webbertakken/unity-actions#41]
I have a few native libraries I load into my Unity project, and it seems to me that the Unity install provided through your Docker instance is defaulting Unity to a 32 bit version?... Not sure if this is correct, but an objdump of my native libraries shows them as 

```
file format elf64-x86-64
```

Am I correct in assuming that I should just build out 32 bit versions? If so, easy support for 64 bit systems should be default, or at least _very_ easy to switch to.

**Comment by webbertakken** [comment]
@GabLeRoux could you pitch in to this one?

Is this correct? and what would we have to do to support this?

**Comment by GabLeRoux** [comment]
yep, I was on my mobile yesterday and didn’t have enough battery to answer ;)

Are we talking about the unity editor binary that is not running as 64bit? Or are we talking about resulting linux artifacts that are 32bit?

**Comment by gblikas** [comment]
@GabLeRoux The former, I believe. I am using the default image via , https://github.com/webbertakken/unity-actions, which is resulting in, what I believe is, a Unity Editor binary that is running as 32 bit: 

```
jobs:
          
  requestActivationAndRunTests:
    name: Request Active Liscene and Run Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Activate Unity
      - name: Unity - Activate
        uses: webbertakken/unity-activate@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          TEST_MODE: all

      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test Results AllModes
          path: ${{ steps.testRunner.outputs.artifactsPath }}
```

When the `webbertakken/unity-test-runner@v1.1` action runs, I get a 
```
Fallback handler could not load library <name> 
// ...
Plugins: Couldn't open Assets/Plugins/x86_64/<name> 
//...
<name>.so invalid ELF header
```

However, an `objdump -h <name>.so` shows that the file format of my library is `file format elf64-x86-64`. The only "strange" flag I built my library with is `-fPIC`, however, I doubt that would cause this problem.
