### ISSUE TITLE
Activate fails on 2019.3.6f1

### ISSUE THREAD

**Issue by Vonr** [webbertakken/unity-actions#58]
**Describe the bug**
Activate fails on 2019.3.6f1 (supported docker image)

**To Reproduce**
1. Attempt License a unity 2019.3.6f1 license (generated from manual activation)

- 

**Expected behavior**
Should have activated and not thrown an error

**Workflow**
```
name: Unity CI

on:
  pull_request: {}
  push: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      - name: Activate Unity
        uses: webbertakken/unity-activate@v1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:  
          unityVersion:  2019.3.6f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.3.6f1
          targetPlatform: StandaloneWindows64 

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```

**Error**
```
Successfully built 46b6f3b43a7c
Successfully tagged unity-action:2019.3.6f1
/usr/bin/docker run --workdir /github/workspace --rm --env UNITY_LICENSE --env UNITY_EMAIL --env UNITY_PASSWORD --env UNITY_SERIAL --env UNITY_VERSION=2019.3.6f1 --env HOME=/github/home --env GITHUB_REF --env GITHUB_SHA --env GITHUB_REPOSITORY --env GITHUB_ACTOR --env GITHUB_WORKFLOW --env GITHUB_HEAD_REF --env GITHUB_BASE_REF --env GITHUB_EVENT_NAME --env GITHUB_WORKSPACE=/github/workspace --env GITHUB_ACTION --env GITHUB_EVENT_PATH --env RUNNER_OS --env RUNNER_TOOL_CACHE --env RUNNER_TEMP --env RUNNER_WORKSPACE --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/runner/work/_temp/_github_home:/github/home --volume /home/runner/work/_temp/_github_workflow:/github/workflow --volume /home/runner/work/TorchOfLife/TorchOfLife:/github/workspace unity-action:2019.3.6f1
Activating Unity version "2019.3.6f1".
Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
##[error]The process '/usr/bin/docker' failed with exit code 1
```
