### ISSUE TITLE
TextMeshPro Does Not Render on Automated Build

### ISSUE THREAD

**Issue by feliperobledo** [webbertakken/unity-actions#62]
**Describe the bug**
Any text mesh pro I add to the scene does not render on a build of the game.

**To Reproduce**

**Unity Version**: 2019.2.17f1
**OS**: macOS

1. Create a new Unity Project
1. Import the plugin `TextMeshPro`
1. Create a UI Panel on the Scene
1. Add a Text Mesh Pro element to the scene
1. Commit to a project with Unity-Actions integrated as build flow and wait for the build artifact
1. Play the game. No text mesh pro text will render

I have a minimalist PR in a public repo I created to reproduce these bugs with as little as possible. You can check it out [here](https://github.com/feliperobledo/sample-unity-project/pull/1).

**Expected behavior**
For Text Mesh Pro Text to render.

**Screenshots**

[Warning Text On Browser]
![Screen Shot 2020-04-24 at 5 54 40 AM](https://user-images.githubusercontent.com/6238302/80200073-1b9ada80-85f0-11ea-9dab-c20fa0ad96fa.png)

[Browser View of Game Built with Unity]
![Screen Shot 2020-04-24 at 6 03 40 AM](https://user-images.githubusercontent.com/6238302/80200961-69641280-85f1-11ea-8ca3-b08a4d82dbbe.png)

[Browser View of Game Built with Github Actions]
![Screen Shot 2020-04-24 at 6 04 37 AM](https://user-images.githubusercontent.com/6238302/80201036-84cf1d80-85f1-11ea-8f30-a5443d231f25.png)

[Directory Text Mesh Pro puts in the Assets Folder]
![Screen Shot 2020-04-24 at 6 06 41 AM](https://user-images.githubusercontent.com/6238302/80201252-d5467b00-85f1-11ea-9aff-b3761a7d8ebb.png)

**Additional context**
When I build the sample scene, I don't get any warnings from the browser telling me that the font is missing.

I might be wrong, but I think this has to do with where in the project directory structure TextMeshPro puts its assets. Somewhere in the build pipeline we are not considering that assets can live at this level. Maybe?

**Comment by DanielParra159** [comment]
I used TextMeshPro in Android porject and it worked well with the action.

Could you try to remove the cache from the workflow? Also is a good idea to have different caches by platform target like this:

 ```
     - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
```
