### ISSUE TITLE
Segmentation fault (core dumped) during license activation (for specific beta versions of unity)

### ISSUE THREAD

**Issue by BlackDereker** [webbertakken/unity-actions#66]
**Describe the bug**
when I try to run the tests and building of my Unity project. It gives me a generic docker error. It has some Segmentation Fault errors but they don't seem to stop the job when they are raised.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/11438830/81329815-77944300-9075-11ea-8fb8-b9b1fa0c89a0.png)

[logs_43.zip](https://github.com/webbertakken/unity-actions/files/4594942/logs_43.zip)

**Comment by webbertakken** [comment]
Hey @BlackDereker and thanks for your bug report.

I'm not sure what the issue is caused by, do you have any idea? What have you tried? Could you test if you have the same issue with unity verison `2019.2.11f1`?

**Comment by BlackDereker** [comment]
Looks like it gives an error when trying to connect to Unity's licensing system. I didn't test on version 2019.2.11f1

![Screenshot_2](https://user-images.githubusercontent.com/11438830/81336604-0312d180-9080-11ea-93ab-760f9444516b.png)

**Comment by KaneFreeman** [comment]
I am receiving the same error when running against version 2020.1.0b9.

![image](https://user-images.githubusercontent.com/1388138/82588344-a677e200-9b68-11ea-9293-33e1076891e4.png)

**Comment by KaneFreeman** [comment]
Here is my config:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.1.1
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.2.0
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.15
        with:
          unityVersion: 2020.1.0b9
          targetPlatform: StandaloneWindows64
          versioning: None

      # Output 
      - uses: actions/upload-artifact@v2.0.1
        with:
          name: Build
          path: build
```

**Comment by webbertakken** [comment]
Thanks everyone for reporting the issues. Please keep posting the versions that suffer from this error.

@KaneFreeman Can you also confirm that these errors are happening consistently (or only once per x runs)?

**Comment by KaneFreeman** [comment]
It is happening on every build. I had the setup previously working on version `2019.3.8f1`.

This was the working config:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.8f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.3.8f1
          targetPlatform: StandaloneWindows64

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```

**Comment by webbertakken** [comment]
@KaneFreeman having compared your two workflows, there are actually a lot of changes, which doesn't really help narrow it down to for example a specific version of unity-builder or of unity (see picture below)

Did you also update the license to one from 2020.1.0b9 or is it crashing because you're using a license that still has an old format?

![image](https://user-images.githubusercontent.com/20756439/82596288-58ce9a00-9ba7-11ea-85fc-7fbed50c2659.png)

**Comment by KaneFreeman** [comment]
Yes I am working to test it more incrementally. I did update the license.

**Comment by KaneFreeman** [comment]
I was able to get the error again just by updating the version.

Here is the config:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2020.1.0b9

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2020.1.0b9
          targetPlatform: StandaloneWindows64

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```
