### ISSUE TITLE
Maximum number of activations

### ISSUE THREAD

**Issue by Denaton** [webbertakken/unity-actions#68]
**Describe the bug**

Fails on Test step
It does not free up the license allocation after usage.

**To Reproduce**

1. Run the Action and let it fail
2. Run it again and licence is not removed

**Expected behavior**

It should remove the machine from licence.

**Additional context**

Here is my workflow file

```yaml
name: Unity to Steam 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_VERSION: 2019.3.13f1 
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows64 

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
  deploy:
      name: Deploy to Steam ☁
      needs: build
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
      steps:
        - name: get commit message
          run: |
           echo ::set-env name=MSG::$(git log --format=%B -n 1 ${{ github.event.after }})
        - uses: actions/checkout@v2
        - uses: webbertakken/steam-deploy@master
          with:
            username: ${{ secrets.STEAM_USERNAME }}
            password: ${{ secrets.STEAM_PASSWORD }}
            appId: ${{ secrets.APP_ID }}
            buildDescription: ${{ env.MSG }}
            rootPath: builds
            depot1Path: StandaloneWindows64
            releaseBranch: unstable
            localContentServer: LocalContentServer
```
[logs_7.zip](https://github.com/webbertakken/unity-actions/files/4617126/logs_7.zip)
