### ISSUE TITLE
unity-test-runner@v1.6 throws docker error (exit code 2) after successfully running tests using Unity 2019.4.8f1

### ISSUE THREAD

**Issue by jordanstudioroot** [webbertakken/unity-actions#85]
**Describe the bug**
Using the standard main.yml provided in the [getting started guide](https://unity-ci.com/docs/github/getting-started) as a template, but substituting in the Unity 2019.4.8f1 image, throws an unspecified docker error and returns exit code of 2. However, the tests successfully run (both passing and failing). As far as I am aware, running failing tests should not throw an error in the docker container.

**To Reproduce**
Run the following workflow on a repository containing edit and play mode tests written for Unity 2019.4.8f1, after obtaining the appropriate license file for the repository and storing it the repository secrets under UNITY_LICENSE:

```
name: Actions 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          unityVersion: 2019.4.8f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.8f1
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```

**Expected behavior**
Regardless of if the other actions (build/output) fail, the tests should run successfully and the test action should be completed.

**Screenshots**
![docker_error](https://user-images.githubusercontent.com/44789812/90912437-3c0d5280-e3a0-11ea-8b7f-3ab4f3a7327d.PNG)

**Additional context**
I have had an identical issue using Unity 2020.1.0f1 as well. I have also had this issue using unity-test-runner@v1.3, and when removing all steps after **Run tests**. It is possible that I am misunderstanding something about how unity-test-runner works, such as if it is supposed to fail if there are failing tests. However, it seems strange that if this is the case, it would throw a docker error.

There is an NSubstitute dll included in the project that I use in the test suite. However, because the tests successfully run I am skeptical that the dll is what is causing the issue.

AFAIK, exit code 2 is returned when an unspecified function is called. However, since the tests run successfully and the error is only caused after the test is run, I'm not sure what could be causing the error.

I apologize if there is missing information from this bug report. This is my first attempt at using any form of continuous integration on a project and there may be some obvious mistake I am making.

Thank you for your time.

**Comment by webbertakken** [comment]
This might be related to https://github.com/webbertakken/unity-actions/issues/84 as it's also concerns one of the latest builds.

**Comment by jordanstudioroot** [comment]
I want to preface this by stating that I am not providing the following approach as a fix or workaround, but rather to add texture to the problem and gauge its similarity to issue #84. Adding a nographics flag, as stated in #84, should not be used as a workaround for backward compatibility issues. That being said...

I modified my main.yml thusly:
```
 # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          unityVersion: 2019.4.8f1
          customParameters: '-nographics'
```

It does not change the output in any way, and instead it produces a warning at the beginning of the test step:

```
##[warning]Unexpected input(s) 'customParameters', valid inputs are ['unityVersion']
```

It is possible I made some mistake in how I am providing the -nographics flag to the action, since I am new to both Github Actions and Unity Actions.
