### ISSUE TITLE
[Question] Build for mobile and web

### ISSUE THREAD

**Issue by jcs090218** [webbertakken/unity-actions#91]
Hi!

I am trying this example project here, https://github.com/Unity-CI/unity-actions-example. And wonder how do I add the test for `Android`, `iOS` and `WebGL`? Here is my `.yml` file, 

* https://github.com/jcs090218/UnityPackageExporter/blob/master/.github/workflows/build.yml

Thanks!

**Comment by GabLeRoux** [comment]
I haven't tried this, but I think that you can create a matrix just like here:  
https://github.com/Unity-CI/unity-actions-example/blob/15fcbf34c2c06edd442dd143f11ae1ebdf65ac4e/.github/workflows/main.yml#L71-L103

in the `with` statement, add a line like `targetPlatform: ${{ matrix.targetPlatform }}` and in the matrix definition (`test.strategy`), add this:

```yaml
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
```

**Comment by jcs090218** [comment]
hmmm... Can you elaborate a little bit more? So basically, I am not able to just do

```yml
...
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
          #- Android
          #- iOS
          #- WebGL
...
```
